baseURL = "http://williamhastings.me/"
languageCode = "en-us"
title = "William Hastings"
theme ="myTheme"
copyright = "Copyright &#xA9; 2017 William Hastings"

[params]
    subtitle = "I'm a Undergraduate Computer Science major with a minor in Mathematics at The Univerversity of Arizona. I am doing what I love, and you can't ask for much more than that!"
    shortsubtitle = "CS Undergrad with a Mathematics Minor. Who knew we could be so funny?!"
    comments = false

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home'></i>"
    weight = -110
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Portfolio"
    pre = "<i class='fa fa-folder-o'></i>"
    weight = -100
    identifier = "portfolio"
    url = "/portfolio/"
[[menu.main]]
    name = "Ramblings"
    pre = "<i class='fa fa-pencil'></i>"
    weight = -90
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "Resume/CV"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = -80
    identifier = "resume"
    url = "/resume/"
[[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-paper-plane-o'></i>"
    weight = -70
    identifier = "contact"
    url = "/contact/"

[[menu.social]]
    name = "Visit me on LinkedIn"
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/william-hastings-03128194/"
    weight = -110
[[menu.social]]
    name = "View my GitHub projects"
    pre = "<i class='fa fa-code-fork'></i>"
    url = "https://github.com/wbhastings"
    weight = -100
[[menu.social]]
    name = "View my BitBucket profile"
    pre = "<i class='fa fa-bitbucket'></i>"
    url = "https://bitbucket.org/wbhastings/"
    weight = -90
[[menu.social]]
    name = "View my Twitter social life"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/willbhastings"
    weight = -80

[permalinks]
blog = "/blog/:monthname/:year/:title/"
